# Generated by Django 3.1.4 on 2020-12-31 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='ate_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='ext',
            new_name='text',
        ),
    ]
